CREATE OR REPLACE TABLE clean.station_5min AS
SELECT DISTINCT
    CAST(timestamp AS TIMESTAMP) AS timestamp,
    CAST(station AS BIGINT) AS station,
    CAST(district AS BIGINT) AS district,
    CAST(freeway AS BIGINT) AS freeway,
    CAST(direction AS VARCHAR) AS direction,
    CAST(lane_type AS VARCHAR) AS lane_type,
    CAST(length AS DOUBLE) AS length,
    CAST(samples AS BIGINT) AS samples,
    CAST(pct_observed AS BIGINT) AS pct_observed,
    CAST(total_flow AS BIGINT) AS total_flow,
    CAST(avg_occupancy AS DOUBLE) AS avg_occupancy,
    CAST(avg_speed AS DOUBLE) AS avg_speed,
    CAST(lane1_samples AS BIGINT) AS lane1_samples,
    CAST(lane1_flow AS BIGINT) AS lane1_flow,
    CAST(lane1_avg_occupancy AS BIGINT) AS lane1_avg_occupancy,
    CAST(lane1_avg_speed AS DOUBLE) AS lane1_avg_speed,
    CAST(lane1_observed AS BOOLEAN) AS lane1_observed,
    CAST(lane2_samples AS BIGINT) AS lane2_samples,
    CAST(lane2_flow AS BIGINT) AS lane2_flow,
    CAST(lane2_avg_occupancy AS BIGINT) AS lane2_avg_occupancy,
    CAST(lane2_avg_speed AS DOUBLE) AS lane2_avg_speed,
    CAST(lane2_observed AS BOOLEAN) AS lane2_observed,
    CAST(lane3_samples AS BIGINT) AS lane3_samples,
    CAST(lane3_flow AS BIGINT) AS lane3_flow,
    CAST(lane3_avg_occupancy AS BIGINT) AS lane3_avg_occupancy,
    CAST(lane3_avg_speed AS DOUBLE) AS lane3_avg_speed,
    CAST(lane3_observed AS BOOLEAN) AS lane3_observed,
    CAST(lane4_samples AS BIGINT) AS lane4_samples,
    CAST(lane4_flow AS BIGINT) AS lane4_flow,
    CAST(lane4_avg_occupancy AS BIGINT) AS lane4_avg_occupancy,
    CAST(lane4_avg_speed AS DOUBLE) AS lane4_avg_speed,
    CAST(lane4_observed AS BOOLEAN) AS lane4_observed,
    CAST(lane5_samples AS BIGINT) AS lane5_samples,
    CAST(lane5_flow AS BIGINT) AS lane5_flow,
    CAST(lane5_avg_occupancy AS BIGINT) AS lane5_avg_occupancy,
    CAST(lane5_avg_speed AS DOUBLE) AS lane5_avg_speed,
    CAST(lane5_observed AS BOOLEAN) AS lane5_observed,
    CAST(lane6_samples AS BIGINT) AS lane6_samples,
    CAST(lane6_flow AS BIGINT) AS lane6_flow,
    CAST(lane6_avg_occupancy AS BIGINT) AS lane6_avg_occupancy,
    CAST(lane6_avg_speed AS DOUBLE) AS lane6_avg_speed,
    CAST(lane6_observed AS BOOLEAN) AS lane6_observed,
    CAST(lane7_samples AS BIGINT) AS lane7_samples,
    CAST(lane7_flow AS BIGINT) AS lane7_flow,
    CAST(lane7_avg_occupancy AS BIGINT) AS lane7_avg_occupancy,
    CAST(lane7_avg_speed AS DOUBLE) AS lane7_avg_speed,
    CAST(lane7_observed AS BOOLEAN) AS lane7_observed,
    CAST(lane8_samples AS BIGINT) AS lane8_samples,
    CAST(lane8_flow AS BIGINT) AS lane8_flow,
    CAST(lane8_avg_occupancy AS BIGINT) AS lane8_avg_occupancy,
    CAST(lane8_avg_speed AS DOUBLE) AS lane8_avg_speed,
    CAST(lane8_observed AS BOOLEAN) AS lane8_observed
FROM raw.station_5min
WHERE timestamp IS NOT NULL AND station IS NOT NULL
ORDER BY station, timestamp;